[package]
name = "micko-rs"
version = "0.1.0"
edition = "2021"
description = "miniC compiler implemented in Rust"

[dependencies]
chumsky = "0.11.2"
ariadne = "0.6.0"
clap = { version = "4.5.53", features = ["derive", "wrap_help"] }
